# mem | postgres
dbtype: postgres
#dbtype: mem

# production | dev
#postgres_env: production
postgres_env: dev

db_ping_timeout: 10 # in seconds

# postgres DB config
postgres_production:
  host: db.serjspends.de
  port: 5432
  name: ispenddb
  user: ubuntu
  password: ''
  sslMode: disable

# in memory DB config
postgres_dev:
  host: localhost
  port: 5432
  name: ispenddb
  user: 2beens
  password: ''
  sslMode: disable