# mem | postgres
dbtype: postgres

# production | dev
postgres_env: dev

db_ping_timeout: 10 # in seconds

# logs dev:    /Users/2beens/Documents/projects/ispend
# logs prod:   /root/ispend
logs_path: /Users/2beens/Documents/projects/ispend

graphite:
  enabled: true
  host: grafana.serjspends.de
  port: 2003

# postgres DB config
postgres_production:
#  host: db.serjspends.de
  host: ec2-3-15-33-157.us-east-2.compute.amazonaws.com
  port: 5432
  name: ispenddb
#  user: ubuntu
  user: ispend
  password: ''
  sslMode: disable

# in memory DB config
postgres_dev:
  host: localhost
  port: 5432
  name: ispenddb
  user: 2beens
  password: ''
  sslMode: disable